nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'Authorization', 'Accept','X-Csrf-Token',X-Xsrf-Token']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~ 