framework:
    rate_limiter:
        api:
            policy: 'token_bucket'
            limit: 200
            rate: { interval: '60 seconds', amount: 10 }
            cache_pool: 'cache.app'
            

