import React from 'react'

const PrivacyEN = () => {
  return (
    <div>
    <p>This Privacy Policy describes Our policies and procedures regarding the collection, use, and disclosure of Your information when You use the Service and informs You of Your privacy rights and how the law protects You.</p>
    <p>We use Your personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy was created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>
    
    <h2>Interpretation and Definitions</h2>
    
    <h3>Interpretation</h3>
    <p>Words with capitalized first letters have meanings defined in the following conditions. The following definitions shall have the same meaning regardless of whether they appear in the singular or plural form.</p>
    
    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
        <li>
            <p><strong>Account</strong> means a unique account created for You to access our Service or certain parts of our Service.</p>
        </li>
        <li>
            <p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where “control” means the ownership of 50% or more of the shares, equity interests, or other voting securities for the election of directors or other management authorities.</p>
        </li>
        <li>
            <p><strong>Company</strong> (referred to as “the Company”, “We”, “Our”, or “Us” in this Agreement) refers to Métamorphose, 1 Rue de Bruxelles, Résidence ALJT, Boîte 88.</p>
        </li>
        <li>
            <p><strong>Cookies</strong> are small files placed on Your computer, mobile device, or other device by a website, containing details of Your browsing history on that site among its many uses.</p>
        </li>
        <li>
            <p><strong>Country</strong> refers to: France</p>
        </li>
        <li>
            <p><strong>Device</strong> means any device that can access the Service, such as a computer, a mobile phone, or a tablet.</p>
        </li>
        <li>
            <p><strong>Personal Data</strong> means any information relating to an identified or identifiable individual.</p>
        </li>
        <li>
            <p><strong>Service</strong> refers to the website.</p>
        </li>
        <li>
            <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service, or assist the Company in analyzing how the Service is used.</p>
        </li>
        <li>
            <p><strong>Usage Data</strong> means data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).</p>
        </li>
        <li>
            <p><strong>Website</strong> refers to Métamorphose, accessible at <a href="https://meta.marcoformante.com" rel="external nofollow noopener" target="_blank">https://meta.marcoformante.com</a></p>
        </li>
        <li>
            <p><strong>You</strong> means the individual accessing or using the Service, or the company, or any other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
        </li>
    </ul>
    
    <h2>Collection and Use of Your Personal Data</h2>
    
    <h3>Types of Data Collected</h3>
    
    <h4>Personal Data</h4>
    <p>When You use Our Service, We may ask You to provide us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
        <li><h4>Usage Data</h4></li>
    </ul>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Usage Data may include information such as Your Device's IP address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, device identifiers, and other diagnostic data.</p>
    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique identifier, Your mobile device's IP address, Your mobile operating system, the type of mobile Internet browser You use, device identifiers, and other diagnostic data.</p>
    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
    
    <h4>Tracking Technologies and Cookies</h4>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
    <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless You have adjusted Your browser setting to refuse Cookies, our Service may use Cookies.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that allow the Company, for example, to count users who have visited those pages or opened an email, and for other site statistics (for example, recording the popularity of a section and verifying system and server integrity).</li>
    </ul>
    <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
    <p>We use Cookies to manage user consent to cookies on our site:</p>
    <ul>
        <li><strong>cookieConsent:</strong> This cookie is set when You accept or refuse cookies via the consent button. It is valid for 300 days and remembers Your choice (accepted or refused).</li>
        <li><strong>cookieConsentUsed:</strong> This session cookie or valid for a duration of two hours is set as soon as You interact with the buttons (accept or refuse). It allows us to ask You later if You wish to reactivate cookies.</li>
    </ul>
    <ul>
        <li><strong>Third-party Cookie (YouTube):</strong>
            <span>On our site, some pages embed YouTube videos (if cookies are accepted), which involves setting YouTube cookies. If You refuse cookies, a link to the video on YouTube is displayed instead of direct embedding.</span>
            <span>For more information on the cookies that YouTube sets, please see YouTube's privacy policy available on their website. You will find details on the types of cookies used, their purpose, and how you can manage your cookie preferences. <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy</a></span>
        </li>
    </ul>
    
    <h3>Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
        <li>
            <p><strong>To provide and maintain our Service</strong>, including to monitor the use of our Service.</p>
        </li>
        <li>
            <p><strong>To contact You:</strong> Responding to a contact request</p>
        </li>
    </ul>   

    <h3>Links to Social Media and Email</h3>
    <p>In addition to cookies used for the functioning of the site, our Service also contains links to third-party platforms such as Instagram and LinkedIn.</p>
    <p>On our contact page, You will find links that direct You to our Instagram and LinkedIn profiles as well as a link to directly email us, which allows You to contact us directly via email. Clicking on these links will redirect You to the external sites of these platforms. These sites may collect data about You, use cookies, integrate additional third-party tracking, and monitor Your interaction with this content, including associating Your interaction with Your account on these platforms (if You are logged in).</p>
    <p>We encourage You to review the privacy policies of these platforms to understand how they collect and use Your personal data. Here are the links to their privacy policies:</p>
    <ul>
        <li><a href="https://privacy.instagram.com/" target="_blank">Instagram Privacy Policy</a></li>
        <li><a href="https://www.linkedin.com/legal/privacy-policy" target="_blank">LinkedIn Privacy Policy</a></li>
    </ul>
</div>
  )
}

export default PrivacyEN